### ISSUE TITLE
OW2 to Open Source Foundations

### ISSUE THREAD

**Issue by aosull01** [OpenIrelandNetwork/learning#8]
https://www.ow2.org/ Description OW2 would be considered an Open Source Foundation that host open source projects Context OW2 could be added to the list of Open Source Foundations, mainly a French community but open to contributions from anywhere Contributor Recommended by: [Adrian OSullivan](https://github.com/aosull01/)

**Comment by mmeagher11** [comment]
Thanks Adrian, I have updated with your recommendation
